### ISSUE TITLE
Facebook on Droid failing with NoSuchMethodError: No virtual method launchUrl

### ISSUE THREAD

**Issue by brittonbeckham** [Clancey/SimpleAuth#42]
It appears that the Facebook login fails to lunch properly (tried it with both the secret and using "native".

```
var apiFb = new FacebookApi("facebook", authProviderInfo.ClientId, "native");
var authenticate = await apiFb.Authenticate();
```

Error:

> **java.lang.NoSuchMethodError: No virtual method launchUrl(Landroid/app/Activity;Landroid/net/Uri;)V in class Landroid/support/customtabs/CustomTabsIntent; or its super classes (declaration of 'android.support.customtabs.CustomTabsIntent' appears in /data/app/com.prepify.app-HbwELJsyQUL0tzsHVqmPfw==/base.apk)**

```
10-18 00:37:34.545 E/AndroidRuntime(18944): java.lang.NoSuchMethodError: No virtual method launchUrl(Landroid/app/Activity;Landroid/net/Uri;)V in class Landroid/support/customtabs/CustomTabsIntent; or its super classes (declaration of 'android.support.customtabs.CustomTabsIntent' appears in /data/app/com.prepify.app-HbwELJsyQUL0tzsHVqmPfw==/base.apk)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at com.facebook.internal.CustomTab.openCustomTab(CustomTab.java:50)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at com.facebook.CustomTabMainActivity.onCreate(CustomTabMainActivity.java:67)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.app.Activity.performCreate(Activity.java:6975)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.os.Looper.loop(Looper.java:164)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at java.lang.reflect.Method.invoke(Native Method)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-18 00:37:34.545 E/AndroidRuntime(18944): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

I spent a considerable amount of time trying to find out where the issue lie. Comparing to your sample application, I have all the needed libraries and versions. Is there anything else you could suggest could be done?

**Comment by Redth** [comment]
What versions of all your nuget packages that are installed?

**Comment by brittonbeckham** [comment]
The only note here is that when I installed `Clancey.SimpleAuth.Facebook.Droid`, it installed `Xamarin.Facebook.Android` v4.16 -- I upgraded to v4.26 to see if it would help.

```
  <package id="Clancey.SimpleAuth" version="1.0.40" targetFramework="monoandroid80" />
  <package id="Clancey.SimpleAuth.Facebook.Droid" version="1.0.3" targetFramework="monoandroid71" />
  <package id="Clancey.SimpleAuth.Google.Droid" version="1.0.9" targetFramework="monoandroid80" />
...
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Build.Download" version="0.4.5" targetFramework="monoandroid71" />
  <package id="Xamarin.Facebook.Android" version="4.26.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.231" targetFramework="monoandroid71" />
  <package id="Xamarin.Google.ZXing.Core" version="3.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Auth" version="42.1021.1" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Auth.Base" version="42.1021.1" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Base" version="42.1021.1" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Basement" version="42.1021.1" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Tasks" version="42.1021.1" targetFramework="monoandroid80" />
```

**Comment by brittonbeckham** [comment]
@Clancey @Redth any other ideas? I'm at a dead end.

**Comment by Redth** [comment]
Are you using proguard? almost seems like something on the java side is being linked away...

**Comment by brittonbeckham** [comment]
Not long after that update, the error ceased. I changed nothing...

Sometimes I either hate programming, or I hate Visual Studio.

**Comment by Redth** [comment]
It's possible there was something cached from older builds still.  When in doubt delete all your obj/ and bin/ folders from your projects in question.

Glad it's working!
