### ISSUE TITLE
Java.Security.UnrecoverableKeyException: no match

### ISSUE THREAD

**Issue by sergio11** [Clancey/SimpleAuth#51]
Hi, I'm using your library for authentication with different social media. In the case of Facebook, I'll do it with a webview. When I use the FacebookApi and show the webview. The following error appears:

![screenshot_20171110-173122](https://user-images.githubusercontent.com/6996211/32668259-535ed978-c63d-11e7-85e4-a549bab61cae.png)

The error that appears in the console is the following:

```
Java.Security.UnrecoverableKeyException: no match
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <7cfbebb561c54efc9010b018c0846c7e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <7cfbebb561c54efc9010b018c0846c7e>:0 
  at Java.Security.KeyStore.GetEntry (System.String alias, Java.Security.KeyStore+IProtectionParameter protParam) [0x00050] in <9ef29c909d7e4606a46b131129da3975>:0 
  at SimpleAuth.AuthStorage.GetSecured (System.String id, System.String clientId, System.String service, System.String sharedGroup) [0x00048] in C:\Projects\SimpleAuth\src\SimpleAuth.Droid\AuthStorage.cs:33 
  at SimpleAuth.AuthenticatedApi.GetAccount[T] (System.String identifier) [0x00002] in C:\Projects\SimpleAuth\src\SimpleAuth\Api\AuthenticatedApi.cs:88 
  --- End of managed Java.Security.UnrecoverableKeyException stack trace ---
java.security.UnrecoverableKeyException: no match
	at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.getObject(BcKeyStoreSpi.java:315)
	at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineGetKey(BcKeyStoreSpi.java:610)
	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:474)
	at java.security.KeyStore.getEntry(KeyStore.java:1560)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.InnerGestureListener.n_onSingleTapUp(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.InnerGestureListener.onSingleTapUp(InnerGestureListener.java:79)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:640)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:54)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:54)
```

How can I solve this error?

**Comment by Clancey** [comment]
That console output is expected for first login. Just letting you know there is nothing cached.  I switched to debug builds which give you more information like that.  As for the facebook error. Can you translate that message? It is most likely an issue with your API Keys, or Redirect URL

**Comment by sergio11** [comment]
Thank you for answering, the translated message is as follows: **"You did not sign in; You did not sign in Log in and try again"**.

I wanted to do it using the Native Facebook SDK, but I need to be able to log out programmatically. I try doing a LoginManager.Instance.Logout () from Android code but the facebook window does not appear again. So I'm going to do it with a WebView where I can use the ResetData () method to do this.

I'm going to explain a little how I do it to see can help me discover the origin of the fault.

I have a provider where I have configured all the information for each social media, in the case of authenticating a child with Facebook is the following:

```
public partial class SonFacebookOAuth2: FacebookOAuth2
    {
		partial void SetPublicNonSensitiveData();
		partial void SetPrivateSensitiveData();

		public SonFacebookOAuth2()
		{
			SetPublicNonSensitiveData();
			SetPrivateSensitiveData();
		}

		partial void SetPublicNonSensitiveData()
		{
			Description = "Facebook OAuth2 WWW App Type Callbackurl http[s]://[www.]xamarin.com";
			OAuth_IdApplication_IdAPI_KeyAPI_IdClient_IdCustomer = "dasdasdasdasd213213";
            OAuth2_Scope = new string[] { "user_likes", "user_photos", "user_posts", "user_relationship_details", "user_relationships", "user_friends" };
			OAuth_UriAuthorization = new Uri("https://m.facebook.com/dialog/oauth/");
            OAuth_UriCallbackAKARedirect = new Uri("fbddddddddddddddddsdsdsd://authorize");
			AllowCancel = true;

}

}
```

Then this provider is passed to the Authentication method where I create an instance of FacebookApi with the clientSecret empty (for now):

```
IObservable<string> InitAuthenticate(OAuthApi api) {

            return Observable.FromAsync(async () =>
            {
                await api.Authenticate();
                return api.CurrentOAuthAccount;
            }).Select((OAuthAccount) => OAuthAccount?.Token);
        }

        public IObservable<string> Authenticate(FacebookOAuth2 oauth2Info, bool reset = false)
        {

            var oautApi = new FacebookApi(
                identifier: "facebook",
                clientId: oauth2Info.OAuth_IdApplication_IdAPI_KeyAPI_IdClient_IdCustomer,
                clientSecret: string.Empty)
            {
                Scopes = oauth2Info.OAuth2_Scope,
            };

            if (reset)
                oautApi.ResetData();

            return InitAuthenticate(oautApi);

        }
```

**Comment by Clancey** [comment]
I am not sure I follow what you are trying to do.  However, I did fix the native login.  https://github.com/Clancey/SimpleAuth/issues/46

**Comment by sergio11** [comment]
Thanks, this new version is available in Nuget Gallery?

**Comment by Clancey** [comment]
Not yet, I will update the nuget at the end of the month, However, you can subclass the `FacebookApi`, and override `ResetData`, and call `LoginManager.Instance.LogOut();` on Android

**Comment by Clancey** [comment]
The nuget is now updated

**Comment by sergio11** [comment]
Thank you very much, I just tried it. After **calling ResetData**, the following screen appears:

> 
> Previously you signed in to BullTect with Facebook.
> Do you want to continue?

![screenshot_20171121-095115](https://user-images.githubusercontent.com/6996211/33063349-851b918c-cea2-11e7-882f-2bcd6bf14f80.png)

How can I get him to ask me for the email and the password to change the user?

**Comment by Clancey** [comment]
Using Facebook Native support this is exactly what it should do. It uses the facebook app to log them in. Facebook doesn't support multiple users. It will always use the account currently logged into facebook.

If you want to support multiple facebook users, or truly switching users don't use facebook native. Just use the built in web auth.
