### ISSUE TITLE
Error processing method: CheckNewGooglePlayServices

### ISSUE THREAD

**Issue by RalphJacobson** [Clancey/SimpleAuth#56]
Since changing Target Framework to use Android 8.0 (Oreo), I'm getting the following error on release builds:

7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void SimpleAuth.Providers.Google/GoogleSignInProvider::CheckNewGooglePlayServices(Android.App.Activity)' in assembly: 'SimpleAuth.Google.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Boolean Android.Gms.Common.Zze::IsUserResolvableError(System.Int32)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    --- End of inner exception stack trace ---
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessEntireQueue()
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process()
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Mono.Linker.Pipeline.Process(LinkContext context)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
7>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1696,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

I'm using the following versions:
Clancey.SimpleAuth 1.0.41
Clancey.SimpleAuth.Google.Droid 1.0.9

(Not using version 1.0.47 of Clancey.SimpleAuth because I'm still using PCL's.)

My linking is set to "Sdk Assemblies Only".

Note that I still get the error even if I include "SimpleAuth;SimpleAuth.Google.Droid" in the "Skip linking assemblies" section.

(It compiles fine if I change the "Linking" to "None", but this is obviously not ideal.)

**Comment by Clancey** [comment]
I would need to look more into it. However you can update. I still support/ship the PCL profile.  https://github.com/Clancey/SimpleAuth/blob/master/SimpleAuth.nuspec#L32

**Comment by Clancey** [comment]
It's this an insue on the latest version? Going to close the issues. Reopen it if it happens in the latest.

**Comment by trevoriancox** [comment]
I'm seeing this issue (linking error in release build) with:
- Clancey.SimpleAuth 1.0.49
- Clancey.SimpleAuth.Google.Droid 1.0.9
- Google Play Services 60.1142.1

**Comment by trevoriancox** [comment]
I am using:

Visual Studio for Mac 7.3.3
Xamarin.Android Version: 8.1.3.0
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3
java version "1.8.0_101"

Sorry no sample project.

**Comment by Clancey** [comment]
You are on older versions of the tooling. Try updating.

**Comment by chisigo** [comment]
I have the same problem. I've updated the sdk build tools and still not working.
I am using the 1.0.49 version
