### ISSUE TITLE
NullReferenceException. TwitterApi on UWP

### ISSUE THREAD

**Issue by KowalskiP** [Clancey/SimpleAuth#60]
Hi
Thanks for your great library =)
I am trying to use twitter for authorization in my app on desktop UWP (Xamarin Forms, NetStandart).
My code:
`
var api = new TwitterApi("twitter", TwitterId, TwitterSecret)
{
RedirectUrl = new Uri("http://mobile.twitter.com")
};
var account = await api.Authenticate();
`
When i input correct email and password, view is providing the dialog to skip or save my credentials. Сhoosing one of this options leads to the only one result - NullReferenceException. This code works fine under macOS.

Stacktrace:
   at System.Collections.Specialized.NameValueCollection.get_Item(String key)
   at SimpleAuth.Providers.TwitterApi.<SendMessage>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SimpleAuth.Api.<SendMessage>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SimpleAuth.Api.<PostMessage>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SimpleAuth.Providers.TwitterApi.<GetAccountFromAuthCode>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SimpleAuth.OAuthApi.<PerformAuthenticate>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SimpleAuth.AuthenticatedApi.<Authenticate>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AudioMiner.BLL.Services.Auth.AuthService.<LoginViaTwitter>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AudioMiner.ViewModels.Sign.SignViewModel.<SignViaSocial>d__19.MoveNext()

**Comment by KowalskiP** [comment]
I found where problem can raised
[here](https://github.com/Clancey/SimpleAuth/blob/81989e635cce4b3aad3925fc9dd84e361e4e233a/src/SimpleAuth/Providers/Twitter.cs#L118) and [here](https://github.com/Clancey/SimpleAuth/blob/81989e635cce4b3aad3925fc9dd84e361e4e233a/src/SimpleAuth/Providers/Twitter.cs#L133)
When I debug sample with Twitter, I find out, that in [NameValueCollection](https://github.com/Clancey/SimpleAuth/blob/81989e635cce4b3aad3925fc9dd84e361e4e233a/src/SimpleAuth.Portable/NameValueCollection.cs#L18) value instead of key is passed

**Comment by Clancey** [comment]
Want to send a pull request?

**Comment by KowalskiP** [comment]
Ofcourse)
I'll send it soon

**Comment by Clancey** [comment]
Nuget updated!
